Please enter the commit message for your changes. Lines starting  with '' will be ignored, and an empty message aborts the commit.
 On branch taglio-17032022
 Your branch is up to date with 'origin/taglio-17032022'.

 Changes to be committed:
	modified:   console
	new file:   lib/foo.sh
	new file:   pdf/Manual_de_instrucciones_GSMOpen.pdf

diff --git a/console b/console
--- a/console
+++ b/console
@@ -1,183 +1,116 @@
 #!/usr/bin/bash
 
-#GLOBAL VAR
+# GLOBAL VAR
 # IPv6 ULA fc00::/7
 # https://howto.lintel.in/speed-ssh-multiplexing/
 
-uid=$(id -u)
-userna=$(id -nu $uid)
-userhome="/home/${userna}"
-proghome="$userhome/Sources/Git/OpenBSD"
-daterelease=$(date +"%d%m%Y%H%m%S")
+# menu
 
+function menu () {
+	local LEVEL="${1}"
 
-
-
-#FUNCTIONS
-
-function passcheck () {
-	z=$(timeout  --preserve-status 5 ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 "${userna}"@"${1}" exit)
-	echo $?
-}
-
-function capa3 () {
-	case "${2}" in
-		"wan")
-			ping -c 1 "${1}" &> /dev/null && echo 1 || echo 0
+	case "${LEVEL}" in
+		0)
+			echo
+			echo -e $0 "-I (Local Domain Name)"
+			echo
 		;;
-		"mesh")
-			[[ $(sshpass -p "${3}" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 admin@${3} :put \([/ping count=1 address="${1}"]=1\) | tail -n 1) == *"true"* ]] && echo 1 || echo 0
+		1)
+            echo
+            echo -e $0 "-I ${LDN} -SO [openbsd|mikrotik|edgeos|ALL] [o]"
+            echo -e $0 "-I ${LDN} -W [o] -> tools on the workstation"
+            echo
 		;;
-	esac
-}
-
-function typeofvar () {
-
-    local type_signature=$(declare -p "$1" 2>/dev/null)
-
-    if [[ "$type_signature" =~ "declare --" ]]; then
-        printf "string"
-    elif [[ "$type_signature" =~ "declare -a" ]]; then
-        printf "array"
-    elif [[ "$type_signature" =~ "declare -A" ]]; then
-        printf "map"
-    else
-        printf "none"
-    fi
-
-}
-
-
-function dnsquery () {
-
-	local ldm="telecom.lobby"
-	local pdm="telecomlobby.com"
-
-	case $(typeofvar $1) in
-		"array")
-			declare -n arr="${1}"
-			case "${2}" in
-				"-FL")
-					r=$(mktemp)
-					dig openbsd."${ldm}" TXT +short > "${r}"
-					dig mikrotik."${ldm}" TXT +short >> "${r}"
-					dig edgeos."${ldm}" TXT +short >> "${r}"
-					for lh in $(cat "${r}" | sed "s/\"//g" | tr \; '\n' | sed '$d'); do
-						arr+=("${lh}")
-					done
-					srm "${r}"
-				;;
-				"-FP")
-					for ph in $(dig ipsec20591."${pdm}" TXT +short @8.8.8.8 | sed "s/\"//g" | tr \; '\n' | sed '$d' | cut -d : -f1); do
-						arr+=("${ph}")
-					done
-				;;
-				*)
-					for lh in $(dig "${2}"."${ldm}" TXT +short | sed "s/\"//g" | tr \; '\n' | sed '$d'); do
-						arr+=("${lh}")
-					done
-				;;
-			esac
-		;;
-		"none")
-			case "${1}" in
-				"-M")
-					for ph in $(dig ipsec20591."${pdm}" TXT +short @8.8.8.8 | sed "s/\"//g" | tr \; '\n' | sed '$d' ); do
-						[[ $(echo "${ph}" | cut -d : -f2) == "${2}" ]] && echo "${ph}" | cut -d : -f1
-					done
-				;;
-			esac
-		;;
-		*)
-			exit 1
+		2)
+			echo
+			echo -e $0 "-I ${LDN} -SO openbsd -N -> newhost [o]"
+            echo -e $0 "-I ${LDN} -SO openbsd -G -> git pull [o]"
+            echo -e $0 "-I ${LDN} -SO openbsd -S -> scripts [o]"
+            echo -e $0 "-I ${LDN} -SO openbsd -D -> dyndnspop [o]"
+            echo -e $0 "-I ${LDN} -SO openbsd -F -> single file update [o]"
+            echo -e $0 "-I ${LDN} -SO openbsd -C -> cleanlast [o]"
+            echo -e $0 "-I ${LDN} -SO openbsd -P -> cleanlast [o]"
+			echo
 		;;
 	esac
+
+	exit 1
 }
 
+# variables from command lines and consequent processing or quit
 
-function strip_ansi() {
-    declare tmp esc tpa re
-    tmp="${1}"
-    esc=$(printf "\x1b")
-    tpa=$(printf "\x28")
-    re="(.*)${esc}[\[${tpa}][0-9]*;*[mKB](.*)"
-    while [[ "${tmp}" =~ $re ]]; do
-        tmp="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
-    done
-    printf "%s" "${tmp}"
-}
-
-function mkrtfilter () {
-	local tmpdir=$(mktemp -d)
-    cp "src/mikrotik/routing_filters.rsc" "${tmpdir}"
-	randomop=$(dig TXT openbsd.telecom.lobby +short | sed "s|\"||g" | tr ";" "\n" | awk NF | shuf -n 1)
-	ospfin=""
-	for host in $(ssh "${randomop}.telecom.lobby" cat /etc/pf.conf.table.{clientes,ipsec} | grep -v \# | awk NF | uniq); do
-		ospfin+=$(printf '%s \n' 'add action=accept chain=ospf-in comment="insert HOST '"${host}"'" prefix='"${host}"' prefix-length=32')
-	done
-	sed -i "s|/OSPFIN/|${osfpin}|" "${tmpdir}/routing_filters.rsc"
-	ospfout=""
-	for host in $(ssh "${randomop}.telecom.lobby" cat /etc/pf.conf.table.{clientes,ipsec} | grep -v \# | awk NF | uniq); do
-		ospfout+=$(printf '%s \n' 'add action=accept chain=ospf-out comment="insert HOST '"${host}"'" prefix='"${host}"' prefix-length=32')
-	done
-	sed -i "s|/OSPFOUT/|${ospfout}|" "${tmpdir}/routing_filters.rsc"
-}
-
-function custom {
-	for file in $(find $1 -type f -maxdepth $2); do
-		(: "${hostname?}") 2>/dev/null && sed -i "s/\/HOSTNAME\//$hostname/g" $file
-		(: "${landomainname?}") 2>/dev/null && sed -i "s/\/LANDOMAINNAME\//$landomainname/g" $file
-		(: "${routerid?}") 2>/dev/null && sed -i "s/\/ROUTERID\//$routerid/g" $file
-		(: "${publichost?}") 2>/dev/null && sed -i "s/\/PUBLICHOST\//$publichost/g" $file
-		(: "${domainname?}") 2>/dev/null && sed -i "s/\/DOMAINNAME\//$domainname/g" $file
-		(: "${srcid?}") 2>/dev/null && sed -i "s/\/SRCID\//$srcid/g" $file
-		(: "${publichostname?}") 2>/dev/null && sed -i "s/\/PUBLICHOSTNAME\//$publichostname/g" $file
-		(: "${publicip?}") 2>/dev/null && sed -i "s/\/PUBLICIP\//$publicip/g" $file
-		(: "${dyndns?}") 2>/dev/null && sed -i "s/\/DYNDNS\//$dyndns/g" $file
-		(: "${publicnetmask?}") 2>/dev/null && sed -i "s/\/PUBLICNETMASK\//$publicnetmask/g" $file
-		(: "${publicbcast?}") 2>/dev/null && sed -i "s/\/PUBLICBCAST\//$publicbcast/g" $file
-		(: "${ipv6egress?}") 2>/dev/null && sed -i "s/\/PUBV6\//${ipv6egress}/g" $file
-		(: "${ipv6prefix?}") 2>/dev/null && sed -i "s/\/PREFIX\//${ipv6prefix}/g" $file
-		(: "${defaultv4router?}") 2>/dev/null && sed -i "s/\/ROUTEV4\//${defaultv4router}/g" $file
-		(: "${ipv6defrouter?}") 2>/dev/null && sed -i "s/\/ROUTEV6\//${ipv6defrouter}/g" $file
-		(: "${longdate?}") 2>/dev/null && sed -i "s/\/LONGDATE\//${longdate}/g" $file
-	done
-}
-
-mac_to_ipv6() {
-    local HWADDR="$1" IFACE="$2"
-    local -a OCTETS
-        local IPV6ADDR
-
-        if [[ -z "$IFACE" ]]; then
-            IFACE=$(ip route | grep ^default | sed 's/^.* dev //')
-        fi
-        OCTETS=( ${HWADDR//:/\ } )
-    OCTETS[0]=$(printf %02x $((16#${OCTETS[0]}+0x02)))
-    IPV6ADDR="fe80::${OCTETS[0]}${OCTETS[1]}:${OCTETS[2]}ff:fe${OCTETS[3]}:${OCTETS[4]}${OCTETS[5]}%$IFACE"
-    echo "$IPV6ADDR"
-}
+(: "${1?}") 2>/dev/null || menu 0
+(: "${2?}") 2>/dev/null && LDN="${2}"
+PDN=$(dig "${LDN}" TXT +short | sed "s|\"||g") && [[ "${PDN}" ]] || ( echo "internal domain name daemon misconfigured or local domain name error" ; exit 1 )
+(: "${3?}") 2>/dev/null || menu 1
+(: "${3?}") 2>/dev/null &&  [ "${3}" == "-SO" ]  || menu 1 && (: "${4?}") 2>/dev/null &&  [ "${4}" == "openbsd"  -o "mikrotik" -o "edgeos" -o "ALL" ] && SO="${4}" || menu 1
+(: "${5?}") 2>/dev/null || menu 2
+(: "${5?}") 2>/dev/null &&  [ "${5}" == "-N" -o "-G" -o "-S" -o "-D" -o "-F" -o "-C" -o "-P" ] && OPT="${5}" || menu 2
 
 # a work array
 
-[[ $(typeofvar wa) == "array" ]] && [[ $(echo ${#wa[@]}) != "0" ]] && unset wa && declare -a wa || declare -a wa
+[[ $(typeofvar wa) == "array" ]] && [[ $(echo ${#wa[@]}) != "0" ]] && ( unset wa && declare -a wa ) || declare -a wa
+
+# variables
+
+userna=$(id -nu ${UID})
+proghome="${HOME}/Sources/Git/OpenBSD"
+daterelease=$(date +"%d%m%Y%H%m%S")
 
 
-if [[ $uid -ne 1000 ]]; then
-	echo -e $0 "you've got to run $0 as UID=1000 \n"
+# temp files
+
+TODAY=$(date +"%d%m")
+RD="/run/user/${UID}/guerrilla"
+[[ -e "${RD}" ]] || mkdir "${RD}"
+for t in $(ls "${RD}"/console-* | grep -v "${TODAY}"); do srm "${t}" ; done
+touch "${RD}"/console-${TODAY}-${RANDOM}
+tf=$(echo $_)
+
+# functions
+
+source "lib/foo.sh"
+
+if [[ "${UID}" -eq 0 ]]; then
+	echo -e $0 "you cannot run $0 as root \n"
 	exit 1
 fi
 
+
+localdomainname=$2
+
+case "${SO}" in
+	"ALL")
+		case "${OPT}" in
+			"-T")
+				echo -e "Launching TMUX"
+				tmux new-session -d -s "LOBBY"
+				dnsquery wa "-FL"
+				for (( j=0; j<${#wa[@]}; j++ )); do
+					echo -e "Creating ${wa[j]} TMUX windows"
+					tmux rename-window "${wa[j]}"
+					tmux send -t "LOBBY:${wa[j]}" ssh SPACE "${wa[j]}.$localdomainname" ENTER
+					tmux new-window
+				done
+				tmux rename-window "CA"
+				tmux send -t "LOBBY:CA" ssh SPACE "ca.$localdomainname" ENTER
+				tmux new-window
+				tmux rename-window $(hostname -s)
+				tmux -2 attach-session -t "LOBBY"
+			;;
+		esac
+	;;
+esac
+
+exit 0
+
 if [[ $# -eq 0 ]]; then
+
 	echo -e $0 "have to be used with the following options \
 			\n \
 			\n-I   -> local domain name [x]\
-			\n-N   -> newhost [o]\
-			\n-G   -> git pull [o]\
-			\n-S   -> scripts [o] \
-			\n-D   -> dyndnspop [o] \
-			\n-F   -> single file update [o] \
-			\n-C   -> cleanlast [o] \
+
+
 			\n-CMK -> clean VPS from Mikrotiks [o] \
 			\n-CEO -> clean VPS from EdgeOS [o] \
 			\n-RS  -> repository ssh update [o] \
@@ -208,25 +141,11 @@ if [[ $# -eq 0 ]]; then
 	exit 1
 fi
 
-localdomainname=$2
 
 
 case $3 in
 	"-T")
-		echo -e "Launching TMUX"
-		tmux new-session -d -s "LOBBY"
-		dnsquery wa "-FL"
-		for (( j=0; j<${#wa[@]}; j++ )); do
-			echo -e "Creating ${wa[j]} TMUX windows"
-			tmux rename-window "${wa[j]}"
-			tmux send -t "LOBBY:${wa[j]}" ssh SPACE "${wa[j]}.$localdomainname" ENTER
-			tmux new-window
-		done
-		tmux rename-window "CA"
-		tmux send -t "LOBBY:CA" ssh SPACE "ca.$localdomainname" ENTER
-		tmux new-window
-		tmux rename-window $(hostname -s)
-		tmux -2 attach-session -t "LOBBY"
+
 	;;
 	"-G"|"-N"|"-S"|"-D"|"-PF"|"-F"|"-C"|"-P")
 		dnsquery wa "openbsd"
@@ -421,7 +340,7 @@ case $3 in
 				srcid=$(echo $a | cut -d : -f2)
 			fi
 		done
-		ssh-keygen -f "${userhome}/.ssh/known_hosts" -R "$publichost"
+		ssh-keygen -f "${HOME}/.ssh/known_hosts" -R "$publichost"
 		scp $ikedpub "${userna}@$publichost:/tmp"
 		openssl pkcs12 -nodes -in $ikedpub -nocerts -passin pass:123456789 -passout pass:123456789 -out "$tmpdir/local.key"
 		openssl pkcs12 -nodes -in $ikedpub -clcerts -nokeys -passin pass:123456789 -passout pass:123456789 -out "$tmpdir/new.crt"
