Please enter the commit message for your changes. Lines starting  with '' will be ignored, and an empty message aborts the commit.
 On branch taglio-08082021
 Your branch is up to date with 'origin/taglio-08082021'.

 Changes to be committed:
	modified:   console

diff --git a/console b/console
--- a/console
+++ b/console
@@ -367,66 +367,53 @@ case $3 in
 		tsig256s=$(dd if=/dev/urandom of=/dev/stdout count=1 bs=64 status=none | openssl base64)
 		tmpupload=$(mktemp)
 		ctrl=
-		while [ -z $ctrl ]
-		do
-			echo "Start configuring $secondarydomain onto master NSD on ${G34[$rand34s]}? "
-			read ctrl
+		while true; do
+			read -p "Start configuring $secondarydomain onto master NSD on ${G34[$rand34s]}? yes/no: " ctrl
+			case $ctrl in
+				[yY]*)
+					echo $masters34gre12 > $tmpupload && echo $masters34gre56 >> $tmpupload && echo ${tsig256s} | tr -d ' ' >> $tmpupload && echo $secondarydomain >> $tmpupload
+					scp $tmpupload "${G34[$rand34s]}.$localdomainname:/tmp/powernsd_distributed" 
+					ssh -o ConnectTimeout=1 -o ConnectionAttempts=1 -t "${G34[$rand34s]}.$localdomainname"  doas sh "/home/taglio/Sources/Git/OpenBSD/setup_node" -D powernsd distributed
+				;;
+				[nN]*)
+					echo 'Ok, going ahead'
+				;;
+				*)
+					echo 'Invalid input' >&2
+			esac
 		done
-		case $ctrl in
-			"yes")
-				tsig256s=$(dd if=/dev/urandom of=/dev/stdout count=1 bs=64 status=none | openssl base64)
-				tmpupload=$(mktemp)
-				echo $masters34gre12 > $tmpupload && echo $masters34gre56 >> $tmpupload && echo ${tsig256s} | tr -d ' ' >> $tmpupload && echo $secondarydomain >> $tmpupload
-				scp $tmpupload "${G34[$rand34s]}.$localdomainname:/tmp/powernsd_distributed" 
-				ssh -o ConnectTimeout=1 -o ConnectionAttempts=1 -t "${G34[$rand34s]}.$localdomainname"  doas sh "/home/taglio/Sources/Git/OpenBSD/setup_node" -D powernsd distributed
-			;;
-			"no")
-			;;
-			*)
-				echo "Type yes or no"
-				continue
-			;;
-		esac
 		ctrl=
-		while [ -z $ctrl ]
-		do
-			echo -e "Continue with configuring $secondarydomain onto slave NSD on ${G12[$rand12s]}? "
-			read ctrl
+		while true; do
+			read -p "Continue with configuring $secondarydomain onto slave NSD on ${G12[$rand12s]}? yes/no: " ctrl
+			case $ctrl in
+				[yY]*)
+					echo $masters34slave12 > $tmpupload && echo ${tsig256s} | tr -d ' ' >> $tmpupload && echo $secondarydomain >> $tmpupload
+					scp $tmpupload "${G12[$rand12s]}.$localdomainname:/tmp/powernsd_distributed" 
+					ssh -o ConnectTimeout=1 -o ConnectionAttempts=1 -t "${G12[$rand12s]}.$localdomainname"  doas sh "/home/taglio/Sources/Git/OpenBSD/setup_node" -D powernsd distributed
+				;;
+				[nN]*)
+					echo 'Ok, going ahead'
+				;;
+				*)
+					echo 'Invalid input' >&2
+			esac
 		done
-		case $ctrl in
-			"yes")
-				
-				echo $masters34slave12 > $tmpupload && echo ${tsig256s} | tr -d ' ' >> $tmpupload && echo $secondarydomain >> $tmpupload
-				scp $tmpupload "${G12[$rand12s]}.$localdomainname:/tmp/powernsd_distributed" 
-				ssh -o ConnectTimeout=1 -o ConnectionAttempts=1 -t "${G12[$rand12s]}.$localdomainname"  doas sh "/home/taglio/Sources/Git/OpenBSD/setup_node" -D powernsd distributed
-			;;
-			"no")
-			;;
-			*)
-				echo "Type yes or no"
-				continue
-			;;
-		esac
 		ctrl=
-		while [ -z $ctrl ]
-		do
-			echo -e "Continue with configuring $secondarydomain onto slave NSD on ${G56[$rand56s]}? "
-			read ctrl
+		while true; do
+			read -p "Continue with configuring $secondarydomain onto slave NSD on ${G56[$rand56s]}? yes/no: " ctrl
+			case $ctrl in
+				[yY]*)
+					echo $masters34slave56 > $tmpupload && echo ${tsig256s} | tr -d ' ' >> $tmpupload && echo $secondarydomain >> $tmpupload
+					scp $tmpupload "${G56[$rand56s]}.$localdomainname:/tmp/powernsd_distributed" 
+					ssh -o ConnectTimeout=1 -o ConnectionAttempts=1 -t "${G56[$rand56s]}.$localdomainname"  doas sh "/home/taglio/Sources/Git/OpenBSD/setup_node" -D powernsd distributed
+				;;
+				[nN]*)
+					echo 'Ok, going ahead'
+				;;
+				*)
+					echo 'Invalid input' >&2
+			esac
 		done
-		case $ctrl in
-			"yes")
-				
-				echo $masters34slave56 > $tmpupload && echo ${tsig256s} | tr -d ' ' >> $tmpupload && echo $secondarydomain >> $tmpupload
-				scp $tmpupload "${G56[$rand56s]}.$localdomainname:/tmp/powernsd_distributed" 
-				ssh -o ConnectTimeout=1 -o ConnectionAttempts=1 -t "${G56[$rand56s]}.$localdomainname"  doas sh "/home/taglio/Sources/Git/OpenBSD/setup_node" -D powernsd distributed
-			;;
-			"no")
-			;;
-			*)
-				echo "Type yes or no"
-				continue
-			;;
-		esac
 		echo -e "Secondary domain $secondarydomain configured"
 	;;
 	"-OM")
